steps:
 - name: 'gcr.io/cloud-builders/mvn'
   entrypoint: 'bash'
   args:
   - '-c'
   - |
    echo "Building branch $BRANCH_NAME @ $REPO_NAME... "

    if [ "$BRANCHNAME" =  "Master" ]; then
      mvn -Dtest=TestMaster test
    elif [ "$BRANCHNAME" = "high-priority-fix" ]; then
      mvn -Dtest=TestHighPriorityFix test
    elif [ "$BRANCHNAME" = "low-priority-fix" ]; then
     mvn -Dtest=TestLowPriorityFix test
    else
    echo "You did not enter a number between 1 and 3."
    fi
