steps:
 - name: 'gcr.io/cloud-builders/mvn'
   entrypoint: 'bash'
   args:
   - '-c'
   - |
    echo "Building branch $BRANCH_NAME @ $REPO_NAME... "
    case $BRANCH_NAME in
      master)
         mvn -Dtest=Test-$BRANCH_NAME test
        ;;
      low-priority-fix)
        mvn -Dtest=Test-$BRANCH_NAME test 
        ;;
      *)
        echo "branch $BRANCH_NAME ignored."
    esac
