steps:
 - name: 'gcr.io/cloud-builders/mvn'
   entrypoint: 'bash'
   args:
   - '-c'
   - |
    echo "Deploying and building branch $BRANCH_NAME @ $REPO_NAME... "
    case $BRANCH_NAME in
      master)
         mvn -Dtest=TestHighPriorityFix test
        ;;
      dev)
        mvn -Dtest=TestLowPriorityFix test
        ;;
      *)
        echo "branch $BRANCH_NAME ignored."
    esac
