steps:
 - name: 'gcr.io/cloud-builders/mvn'
   entrypoint: 'bash'
   args:
   - '-c'
   - |
    echo "Building branch $BRANCH_NAME @ $REPO_NAME... "

    if [ "$BRANCH_NAME" =  "Master" ]; then
      mvn -Dtest=TestMaster test |
      mvn package
    elif [ "$BRANCH_NAME" = "high-priority-fix" ]; then
      mvn -Dtest=TestHighPriorityFix test |
      mvn package
    elif [ "$BRANCH_NAME" = "low-priority-fix" ]; then
     mvn -Dtest=TestLowPriorityFix test |
     mvn package
    else
    echo "If a new branch create one more if condition."
    fi
